In [8]:
import pandas as pd

# Import dataset
df = pd.read_csv("/content/iris.csv")

# Clean column names to remove any leading/trailing spaces (if any)
df.columns = df.columns.str.strip()

# Check the column names to ensure 'species' or the correct column exists
print(df.columns)

# Print the first few rows to check if 'species' exists
print(df.head())

# Assuming the column is 'Species' (with a capital 'S')
# Correct column name (assuming it is 'Species')
print(df['Species'].unique())


# Import label encoder
from sklearn import preprocessing

# Create label_encoder object
label_encoder = preprocessing.LabelEncoder()

# Encode labels in the 'Species' column (update the column name if necessary)
df['Species'] = label_encoder.fit_transform(df['Species'])

# Print unique encoded values
print(df['Species'].unique())


Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')
   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


KeyError: 'Species'

In [6]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

# Define data (colors as an example)
data = asarray([['red'], ['green'], ['blue']])
print("Original Data:")
print(data)

# Define ordinal encoding
encoder = OrdinalEncoder()

# Transform data using OrdinalEncoder
result = encoder.fit_transform(data)

# Print the encoded result
print("Encoded Data:")
print(result)


Original Data:
[['red']
 ['green']
 ['blue']]
Encoded Data:
[[2.]
 [1.]
 [0.]]


In [10]:
from sklearn.preprocessing import OneHotEncoder

# Define data (colors as an example)
data = [['red'], ['green'], ['blue']]
print("Original Data:")
print(data)

# Define OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Transform data using OneHotEncoder
onehot = encoder.fit_transform(data)

# Print the one-hot encoded result
print("One-Hot Encoded Data:")
print(onehot)


Original Data:
[['red'], ['green'], ['blue']]
One-Hot Encoded Data:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
